@port = 5000
@Host =  http://localhost
@route = api/v1/users


###

GET {{Host}}:{{port}}/{{route}}?role=admin

###

GET {{Host}}:{{port}}/{{route}}/bob

###


DELETE {{Host}}:{{port}}/{{route}}/612d7a49eb142b3d64fbd584 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmI3ZDAyOWE3NGZlMzRhYzFkZTM5YyIsImlhdCI6MTYzMDQ0MDkwNSwiZXhwIjoxNjM4MTMwNTA1fQ.qQ0yDOmmaAVOPPSSlwb7YOIn7N_VGJ-MfmpxKcjbmn8

###

PATCH {{Host}}:{{port}}/{{route}}/612e92cac3d6533558e08307 
Content-Type: application/json

{
    "name":"nur"
}


###

PATCH {{Host}}:{{port}}/{{route}}/612e92cac3d6533558e08307
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzQ4NzdmZjY0Y2YyM2MyODczNzE3YiIsImlhdCI6MTYzMDkyMzgxOSwiZXhwIjoxNjM4NjEzNDE5fQ.GW0b5FhW1nznjKPkfxs4SnES3wF6Mw4vWb_22l1h-9Q
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

PATCH  {{Host}}:{{port}}/{{route}}/updateMe 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMzQ4NzdmZjY0Y2YyM2MyODczNzE3YiIsImlhdCI6MTYzMDkyMzgxOSwiZXhwIjoxNjM4NjEzNDE5fQ.GW0b5FhW1nznjKPkfxs4SnES3wF6Mw4vWb_22l1h-9Q
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photo"; filename="1.png"
Content-Type: image/png

< ../dev-data/img/new-tour-1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



###

DELETE {{Host}}:{{port}}/{{route}}/deleteMe 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmI3ZDAyOWE3NGZlMzRhYzFkZTM5YyIsImlhdCI6MTYzMDQ0MDkwNSwiZXhwIjoxNjM4MTMwNTA1fQ.qQ0yDOmmaAVOPPSSlwb7YOIn7N_VGJ-MfmpxKcjbmn8


###

GET  {{Host}}:{{port}}/{{route}}/me 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmU5MmNhYzNkNjUzMzU1OGUwODMwNyIsImlhdCI6MTYzMDQ2NjU2MiwiZXhwIjoxNjM4MTU2MTYyfQ.xlw4G4WNGYTgyhOEPt9qlurpBC27zSB2tAoYqPO1K2Q
